### ISSUE TITLE
Social Auth Migrations in 1.2

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#130]
I got the following error when running migrations on the demo server when upgrading to 1.2. 

Running migrations:
  Applying default.0001_initial...Traceback (most recent call last):
  File "/usr/lib/tethys/src/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 36, in database_forwards
    schema_editor.create_model(model)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/schema.py", line 270, in create_model
    self.execute(sql, params)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "social_auth_association" already exists

**Comment by sdc50** [comment]
Nathan,

I'm happy to look into this if you don't have time. I think that you had mentioned something about this error, and that the social_auth_association table was used in 1.0, or something like that? I think we should include instructions in the update documentation to handle it, or write some code in the migration to drop the social_auth_association table if it exists.

I dropped the the table for the demo server and then was able to run the migration. I hope that wasn't a bad thing to do.

**Comment by sdc50** [comment]
Drew worked around this issue by doing the following: 

I manually dropped three tables under tethys_default:
social_auth_association
social_auth_usersocialauth
social_auth_nonce
