### ISSUE TITLE
Tethys Compute Migration Error in 1.2

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#131]
I got the following error when running migrations on the demo server when upgrading to 1.2:  

 Applying default.0004_auto_20150818_2259... OK
  Applying tethys_compute.0004_auto_20150812_1915...Traceback (most recent call last):
  File "/usr/lib/tethys/src/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/schema.py", line 91, in __exit__
    self.execute(sql)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/tethys/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: insert or update on table "tethys_compute_condorjob" violates foreign key constraint "te_scheduler_id_30b5e6b094e4c9ca_fk_tethys_compute_scheduler_id"
DETAIL:  Key (scheduler_id)=(1) is not present in table "tethys_compute_scheduler".

**Comment by sdc50** [comment]
The problem is that I'm trying to assign a default foreign key in the condorjobs table, that points to a scheduler, but the scheduler table is empty because it was just created. I ended up getting past this by deleting all of the jobs that were in the database.

I should fix this either by initializing the scheduler table with a default scheduler, or by making the scheduler field in the condorjobs table nullable and removing the default initialize value.

**Comment by sdc50** [comment]
This was fixed by making the scheduler field nullable as part of hotfix 1.2.3. It is assumed that if the scheduler is null then jobs will be submitted to the localhost, so HTCondor must be installed on the Tethys server (documentation for that is underway). 

When upgrading to 1.2.3 it is necessary to run:

tethys manage syncdb
 and 
tethys manage collectall
