### ISSUE TITLE
Django settings error encountered when trying to run pip install or setup tools

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#179]
We encountered this error when trying to update requirements with certain apps installed. We have discovered that this happens because pip tries to load each python package, including our app package, epanet. The **init**.py of our app package imports something from app.py, which launches an import chain that results trying to import a module that is dependent on the Django settings being initialized. The Django settings have not been initialized, because we are running a pip operation, which results in the exception.

This is a variation of Issue #176. 

Here is the full trace:

$ pip install --update -r requirements.txt 
Traceback (most recent call last):
  File "/usr/lib/tethys/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/**init**.py", line 9, in <module>
    from pip.log import logger
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/log.py", line 9, in <module>
    from pip._vendor import colorama, pkg_resources
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2717, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 682, in subscribe
    callback(dist)
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2717, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2255, in activate
    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 1863, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 1832, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/nswain/svn/tethys/tethysapp-epanet/branches/annotations/tethysapp/epanet/__init__.py", line 19, in <module>
    from tethysapp.epanet.app import LOG_PATH, LOG_LEVEL
  File "/home/nswain/svn/tethys/tethysapp-epanet/branches/annotations/tethysapp/epanet/app.py", line 12, in <module>
    from tethys_sdk.jobs import CondorJobTemplate
  File "/usr/lib/tethys/src/tethys_sdk/jobs.py", line 11, in <module>
    from tethys_compute.job_manager import (JobManager,
  File "/usr/lib/tethys/src/tethys_compute/job_manager.py", line 11, in <module>
    from tethys_compute.models import TethysJob, CondorJob, BasicJob
  File "/usr/lib/tethys/src/tethys_compute/models.py", line 11, in <module>
    from django.contrib.auth.models import User
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 50, in AbstractBaseUser
    password = models.CharField(_('password'), max_length=128)
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1072, in **init**
    super(CharField, self).**init**(_args, *_kwargs)
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 166, in **init**
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/conf/**init**.py", line 55, in **getattr**
    self._setup(name)
  File "/usr/lib/tethys/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by swainn** [comment]
I see potentially two solutions to this:

1. We assume/strongly recommend that no imports happen at the base __init__.py of the module and fix EPANET accordingly, which means refactoring the logging (which I want done anyway, but probably isn't the highest priority).

2. We assume developers will make the same mistake we did and instead make sure tethys (tethys_compute in this case) is very careful with app imports (e.g.: wrapped in try/except, or explicitly define __all__ might work too).

The reason I might lean toward option 2 is because this sort of error prone import chain can be encountered fairly easily in other more common instances, such as when a module containing controllers imports something from a Django app or when a model imports something from a Django app. I think the solution may be as simple as:

try:
    from django.contrib.auth.models import User
except django.core.exceptions.ImproperlyConfigured as e:
    # do the trick that loads the app and sets reasonable default/null values for django settings that are necessary
    from django.contrib.auth.models import User

Essentially, we assume that we only get into the except block when the module is imported outside of initialized Django settings, so we don't really care if the settings are valid or not, just that they are there so we don't the exceptions.

**Comment by swainn** [comment]
The comment in the except block that says "do the trick that loads the app and sets reasonable default/null values for django settings that are necessary" can be a fairly annoying and repetitive thing to do on a frequent basis, so we may want to create a function that can be called which will do that for us...

**Comment by swainn** [comment]
We recommend following suggestion 1 in my comment above to avoid this and similar issues. In general, to avoid settings initialization problems, avoid importing django settings or any django models (e.g. User) at the top of modules and instead import them within the scope of the function or method where they will be used (Python allows this).
