### ISSUE TITLE
tethys syncstores issue - callable

### ISSUE THREAD

**Issue by snowman2** [tethysplatform/tethys#185]
On the dev branch, when I attempt to run:

$tethys syncstores dam_break

Traceback (most recent call last):
  File "/usr/lib/tethysdev/src/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/tethysdev/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/tethysdev/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/tethysdev/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/tethysdev/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/tethysdev/src/tethys_apps/management/commands/syncstores.py", line 45, in handle
    self.provision_persistent_stores(options['app_name'], options)
  File "/usr/lib/tethysdev/src/tethys_apps/management/commands/syncstores.py", line 122, in provision_persistent_stores
    persistent_stores = app.persistent_stores()
  File "/usr/lib/tethysdev/src/tethys_apps/tethysapp/dam_break/app.py", line 51, in persistent_stores
    spatial=True
  File "/usr/lib/tethysdev/src/tethys_apps/base/persistent_store.py", line 94, in __init__
    super(PersistentStore, self).__init__(self.initializer)
  File "/usr/lib/tethysdev/src/tethys_apps/base/persistent_store.py", line 31, in __init__
    if path.callable():
AttributeError: 'str' object has no attribute 'callable'

What is going on? What am I missing?

**Comment by snowman2** [comment]
Issue fixed with this merge: https://github.com/tethysplatform/tethys/pull/182/commits/1f67ffa5c3537ed2f9380c0f86139e7758a676b7
