### ISSUE TITLE
HTCondor "getcwd() is not found" error

### ISSUE THREAD

**Issue by shawncrawley** [tethysplatform/tethys#306]
The environment of an app occasionally gets "out of sync" with regard to the current working directory being used by HTCondor. I was told by @swainn that this is something that he thought had been addressed and patched up, but it has definitely resurfaced. I'm trying to gauge if this is actually something that I could just work around in my code (or is actually caused by my code), but I was hoping that @sdc50 could comment on this and suggest if it is actually a bug in Tethys core that can again be addressed.

Here is the traceback that I get when the error occurs:

``` bash
[Fri Jun 30 20:21:09.083360 2017] [wsgi:error] [pid 3559519] Traceback (most recent call last):
[Fri Jun 30 20:21:09.083395 2017] [wsgi:error] [pid 3559519] File "/usr/lib64/tethys/src/tethys_apps/tethysapp/epanet/controllers/manage/project.py", line 233, in modify_project
[Fri Jun 30 20:21:09.083501 2017] [wsgi:error] [pid 3559519] job.run_job()
[Fri Jun 30 20:21:09.083529 2017] [wsgi:error] [pid 3559519] File "/var/www/tethys/apps/tethysapp-citywater/tethysapp/epanet/lib/condor_file_read_job.py", line 158, in run_job
[Fri Jun 30 20:21:09.083565 2017] [wsgi:error] [pid 3559519] self.workflow.execute()
[Fri Jun 30 20:21:09.083577 2017] [wsgi:error] [pid 3559519] File "/usr/lib64/tethys/src/tethys_compute/models.py", line 385, in execute
[Fri Jun 30 20:21:09.083613 2017] [wsgi:error] [pid 3559519] self._execute(*args, **kwargs)
[Fri Jun 30 20:21:09.083624 2017] [wsgi:error] [pid 3559519] File "/usr/lib64/tethys/src/tethys_compute/models.py", line 792, in _execute
[Fri Jun 30 20:21:09.083649 2017] [wsgi:error] [pid 3559519] super(self.__class__, self)._execute(options=options)
[Fri Jun 30 20:21:09.083660 2017] [wsgi:error] [pid 3559519] File "/usr/lib64/tethys/src/tethys_compute/models.py", line 546, in _execute
[Fri Jun 30 20:21:09.083681 2017] [wsgi:error] [pid 3559519] self.cluster_id = self.condor_object.submit(*args, **kwargs)
[Fri Jun 30 20:21:09.083692 2017] [wsgi:error] [pid 3559519] File "/usr/lib/tethys/lib/python2.7/site-packages/condorpy/workflow.py", line 173, in submit
[Fri Jun 30 20:21:09.083723 2017] [wsgi:error] [pid 3559519] self._write_job_file()
[Fri Jun 30 20:21:09.083734 2017] [wsgi:error] [pid 3559519] File "/usr/lib/tethys/lib/python2.7/site-packages/condorpy/workflow.py", line 207, in _write_job_file
[Fri Jun 30 20:21:09.083749 2017] [wsgi:error] [pid 3559519] dag_file = self._open(self.dag_file, 'w')
[Fri Jun 30 20:21:09.083759 2017] [wsgi:error] [pid 3559519] File "/usr/lib/tethys/lib/python2.7/site-packages/condorpy/htcondor_object_base.py", line 108, in wrapped
[Fri Jun 30 20:21:09.083794 2017] [wsgi:error] [pid 3559519] cwd = os.getcwd()
[Fri Jun 30 20:21:09.083824 2017] [wsgi:error] [pid 3559519] OSError: [Errno 2] No such file or directory
```

**Comment by swainn** [comment]
Could be that getcwd is not thread safe...
