### ISSUE TITLE
The testing platform does not work as expected

### ISSUE THREAD

**Issue by pythonweb2** [tethysplatform/tethys#344]
I think that the there is something wrong with the tethys testing suite. I simply tried to run the basic default example tests and I got an error when I ran the command `tethys test -f tethys_apps.tethysapp.statistics_calc.tests.tests.StatisticsCalcTestCase`. 

The error is below.

`Traceback (most recent call last):
 File "/home/wade/tethys/src/manage.py", line 20, in <module>
   execute_from_command_line(sys.argv)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
   utility.execute()
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
   super(Command, self).run_from_argv(argv)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
   output = self.handle(*args, **options)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in handle
   failures = test_runner.run_tests(test_labels)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/test/runner.py", line 600, in run_tests
   suite = self.build_suite(test_labels, extra_tests)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/test/runner.py", line 484, in build_suite
   tests = self.test_loader.loadTestsFromName(label)
 File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
   parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'tests'`

**Comment by sdc50** [comment]
Are you sure about module path? The error makes it seem like the second
".tests" is superfluous.

**Comment by waderoberts123** [comment]
It could be but I just copied that verbatim from the current documentation. So I will try it again and let you know, but the documentation should be changed.

**Comment by waderoberts123** [comment]
Update on the issue. I went ahead and scaffolded a new app, and the command seems to work, however, it says that I don't have the correct permissions to create a test database. The error message for that is below. 

```
(tethys) wade@wade-HP-EliteDesk-800-G1-SFF:~$ tethys test -f tethys_apps.tethysapp.test_application.tests.tests.TestApplicationTestCase
Loading Tethys Apps...
Tethys Apps Loaded: statistics_calc test_application
Loading Tethys Apps...
Tethys Apps Loaded: statistics_calc test_application
Creating test database for alias 'default'...
Got an error creating the test database: permission denied to create database

Type 'yes' if you would like to try deleting the test database 'test_tethys_default', or 'no' to cancel: no
Tests cancelled.
```

So then I tried to do what the docstring in the tests.py file said, which is to change the settings.py file. So I went to ```~/tethys/src/tethys_portal/settings.py```, line 156 and changed ```tethys_default``` to `tethys_super`, which then caused this error.

```
(tethys) wade@wade-HP-EliteDesk-800-G1-SFF:~$ tethys test -f tethys_apps.tethysapp.test_application.tests.tests.TestApplicationTestCase
Loading Tethys Apps...
Tethys Apps Loaded: statistics_calc test_application
Loading Tethys Apps...
Tethys Apps Loaded: statistics_calc test_application
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/home/wade/tethys/src/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 55, in create_test_db
    self._create_test_db(verbosity, autoclobber, keepdb)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 164, in _create_test_db
    with self._nodb_connection.cursor() as cursor:
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/wade/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "tethys_super" does not exist
```

So the original error in the app I am developing might have something to do with the path, but why is it saying that the role `tethys_super` does not exist?

**Comment by sdc50** [comment]
I'm assuming that you are using the locally created database and not the
PostGIS Docker, is that correct. The local database (at least in the
version of the install script that was released with 2.0) does not set up a
tethys_super user. If you want to manually set one up you can look at the
install script to see how:
https://github.com/tethysplatform/tethys/blob/master/scripts/install_tethys.sh#L360-L361.
You could also try just deleting your whole local database and using the
most recent version of the install script to create a new database. Refer
to the new option: --partial-tethys-install
<http://docs.tethysplatform.org/en/latest/installation/linux_and_mac.html>.

**Comment by waderoberts123** [comment]
Will creating a new database allow me to create a super user?

**Comment by sdc50** [comment]
You should be able to creat the super user with your current database.
Alternatively, if you create a new database with the latest install script
then it will create the super user for you.

**Comment by swainn** [comment]
Closing due to inactivity. Possibly the same issue as in #640 and #888
