### ISSUE TITLE
docker permission denied

### ISSUE THREAD

**Issue by john3641** [tethysplatform/tethys#428]
I'm using Ubuntu 18.04 LTS (bionic) in Oracle VM Box.  I installed tethys with docker options as follows:

bash install_tethys.sh -b master --install-docker --docker-options "'-d -c geoserver'"

During the execution, I got a warning  that 
tethys.tethys_quotas.apps: Unable to sync resource quota handlers: Resource Quota table does not exist

But otherwise all seemed to install well.  But I couldn't get Docker to connect.  I tried re-installing tethys without the Docker options, and then installed Docker manually, following the Docker documentation.  I got it to report "Hello World" to verify installation by 

(tethys) john@john-VirtualBox:-$ sudo docker run hello-world 

though it asks for my Ubuntu system password.  

I get permission denied when I leave out "sudo", even though I had logged back out and back in.  The message reads:  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock...

I tried adding users for Docker permissions to default names used in the tethys platform - admin, tethys_super, and even my own name for the Ubuntu operating system with

(tethys) john@john-VirtualBox:~$ sudo usermod -aG docker $tethys_super, 

logged out, even restarted machine, but still no luck.  

And not surprisingly, I keep getting 
PermissionError: [Errno 13] Permission denied when trying 

(tethys) john@john-VirtualBox:-$ tethys docker start

as stated in the tutorial. 

I'm stumped.  Any ideas on what to try next?

Here's some  of the report from the terminal:
john@john-VirtualBox:~$ t
(tethys) john@john-VirtualBox:~$ tethys docker start
Loading Tethys Extensions...
Loading Tethys Apps...
Tethys Apps Loaded: 

Traceback (most recent call last):
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/john/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638,

**Comment by swainn** [comment]
Try running:
sudo usermod -aG docker $USER
Then logout and log back in and try:
docker ps
If you don't get permission denied, then try:
tethys docker init

**Comment by john3641** [comment]
Thanks, Swainn, that worked! I'm fairly new to using cli in Ubuntu, and thought I should put an actual username where the sudo command has USER, and then I saw no error when I made that mistake.  Anyway, thanks.

**Comment by swainn** [comment]
Glad it worked out! I recommend you check out our forum if you haven't already. There's a pretty good community there: https://groups.google.com/forum/#!forum/tethysplatform
