### ISSUE TITLE
install geoserver docker failed

### ISSUE THREAD

**Issue by gaoxiang123456789** [tethysplatform/tethys#444]
Here is a specific problems:

Bind the GeoServer data directory to the host? [Y/n]: y
Specify location to bind data directory [/home/gaoxiang/tethys/geoserver/data]: /home/gaoxiang/tethys/geoserver/data/a
Traceback (most recent call last):
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=tethys_geoserver

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaoxiang/miniconda/envs/tethys/bin/tethys", line 11, in <module>
    load_entry_point('tethys-platform', 'console_scripts', 'tethys')()
  File "/home/gaoxiang/tethys/tethys/tethys_cli/__init__.py", line 55, in tethys_command
    args.func(args)
  File "/home/gaoxiang/tethys/tethys/tethys_cli/docker_commands.py", line 682, in docker_command
    docker_init(containers=args.containers, defaults=args.defaults)
  File "/home/gaoxiang/tethys/tethys/tethys_cli/docker_commands.py", line 564, in docker_init
    install_docker_containers(containers_to_install, defaults=defaults)
  File "/home/gaoxiang/tethys/tethys/tethys_cli/docker_commands.py", line 547, in install_docker_containers
    container_metadata.create(defaults)
  File "/home/gaoxiang/tethys/tethys/tethys_cli/docker_commands.py", line 164, in create
    self.docker_client.api.create_container(**options)
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/docker/api/container.py", line 429, in create_container
    return self.create_container_from_config(config, name)
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/docker/api/container.py", line 440, in create_container_from_config
    return self._result(res, True)
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/gaoxiang/miniconda/envs/tethys/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: ciwater/geoserver:2.8.2-clustered")

**Comment by swainn** [comment]
I believe this is functional now. The `tethys docker` command should be retrieving the `tethysplatform/gesoerver:<tag>` image.
