### ISSUE TITLE
tethys db configure     error

### ISSUE THREAD

**Issue by gaowudao** [tethysplatform/tethys#502]
(tethys) gaoxiang@gaoxiang-VirtualBox:~$ tethys db configure
Traceback (most recent call last):
  File "/home/gaoxiang/anaconda3/envs/tethys/bin/tethys", line 10, in <module>
    sys.exit(tethys_command())
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/site-packages/tethys_cli/__init__.py", line 64, in tethys_command
    args.func(args)
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/site-packages/tethys_cli/db_commands.py", line 184, in db_command
    options = process_args(args)
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/site-packages/tethys_cli/db_commands.py", line 149, in process_args
    db_settings = settings.DATABASES[args.db_alias]
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/gaoxiang/anaconda3/envs/tethys/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'tethys_portal.settings'**

**Comment by swainn** [comment]
@gaowudao please try using the latest development version.
