### ISSUE TITLE
siphon needs to be included as a dependency in the conda build

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#510]
It looks like `siphon` is now required by `tethys_services.models`. It was added to the `env.yml` but not to the conda recipe, so the most recent dev builds of tethys don't include the library. This results in an error when trying to run migrations on the database:

```
Traceback (most recent call last):
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/tethys_portal/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/tethys_apps/models.py", line 22, in <module>
    from tethys_services.models import validate_url
  File "/home/rditlsc9/miniconda/envs/tp1/lib/python3.7/site-packages/tethys_services/models.py", line 14, in <module>
    from siphon.catalog import TDSCatalog
ModuleNotFoundError: No module named 'siphon'
```

**Comment by swainn** [comment]
@sdc50 I noticed that last night as well. I forgot that the conda recipe is not being auto generated at this time. I'll add it to the conda build.
