### ISSUE TITLE
Tethys 2.0 to Tethys 3.0 Upgrade config file documentation error

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#537]
Documentation for upgrading to Tethys 3.0 seems to have an error on the site_content section of the portal_config.yml file. The old version of the site settings database uses "Footer Copyright" and the documentation says to use "COPYRIGHT" in the YAML file. Changing the YAML file from "COPYRIGHT: 'VALUE'" to "FOOTER_COPYRIGHT: 'VALUE'" solves the error. 

COMMAND:
> (tethys): $ tethys site -f ~/tethys/portal_config.yml

ERROR:

> Traceback (most recent call last):
  File "/home/ezra/tethys/miniconda/envs/tethys/bin/tethys", line 10, in <module>
    sys.exit(tethys_command())
  File "/home/ezra/tethys/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_cli/__init__.py", line 66, in tethys_command
    args.func(args)
  File "/home/ezra/tethys/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_cli/site_commands.py", line 177, in gen_site_content
    obj = Setting.objects.filter(name=arg_filter[arg.lower()])
KeyError: 'copyright'

**Comment by swainn** [comment]
This will be fixed in #532
