### ISSUE TITLE
How to install Tethys 2.1.7

### ISSUE THREAD

**Issue by melpham** [tethysplatform/tethys#620]
I have to support one of our apps that is still using Tethys 2.1.7. Documentation says to install version 2.1.7 through the bash command "bash install_tethys.sh -b release". I was wondering which branch I should use to install version 2.1.7? https://github.com/tethysplatform/tethys/branches/all

**Comment by swainn** [comment]
@melpham I don't think we've maintained a branch for 2.1.7. However, we do have a 2.1.7 tagged commit: https://github.com/tethysplatform/tethys/tree/2.1.7 You could checkout that.

**Comment by melpham** [comment]
@swainn  okay thanks. I downloaded the install script at https://raw.githubusercontent.com/tethysplatform/tethys/2.1.7/scripts/install_tethys.sh and changed the git checkout from the branch to the 2.1.7 tag. It successfully cloned that repository but when setting up the environment, I am getting an error like the below.


`Installing tethys script to /home/melissa/miniconda3/envs/tethys/bin

Installed /home/melissa/tethys/src
Processing dependencies for tethys-platform==2.1.3
Finished processing dependencies for tethys-platform==2.1.3
Traceback (most recent call last):
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/melissa/miniconda3/envs/tethys/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

`

**Comment by melpham** [comment]
@swainn okay thanks. I downloaded the install script at https://raw.githubusercontent.com/tethysplatform/tethys/2.1.7/scripts/install_tethys.sh and changed the git checkout from the branch to the 2.1.7 tag. It successfully cloned that repository but when setting up the environment, I am getting an error like the below.

`Installing tethys script to /home/miniconda3/envs/tethys/bin

Installed /home/tethys/src
Processing dependencies for tethys-platform==2.1.3
Finished processing dependencies for tethys-platform==2.1.3
Traceback (most recent call last):
File "/home/miniconda3/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
chunked=chunked,
File "/home/miniconda3/envs/tethys/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/home/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1239, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/home/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1285, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/home/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1234, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/home/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 1026, in _send_output
self.send(msg)
File "/home/miniconda3/envs/tethys/lib/python3.6/http/client.py", line 964, in send
self.connect()
File "/home/miniconda3/envs/tethys/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

`

**Comment by swainn** [comment]
Hi @melpham seems like there is an issue with Docker. I'm guessing it's due to either Docker not being installed and running, or Tethys is installing an old version of the Docker python API that doesn't work with the newer versions of Docker. Unfortunately, we don't have the bandwidth to support multiple versions of Tethys at this time, so we aren't doing bug fixes for anything prior to the current version.

Have you considered migrating your app to Tethys 3? We have a guide in our documentation that describes what needs to be done. For most apps, it is a fairly straightforward and quick process:

http://docs.tethysplatform.org/en/stable/whats_new/app_migration.html?highlight=Migrate
