### ISSUE TITLE
Error when configuring database during install

### ISSUE THREAD

**Issue by GanapatiN** [tethysplatform/tethys#676]
Error when doing "tethys db configure" on Ubuntu 20.04 Focal. Previous install steps are fine

Output as below: 

Initializing Postgresql database server in "/home/ganapati/.tethys/psql/data"...
The files belonging to this database system will be owned by user "ganapati".
This user must also own the server process.

The database cluster will be initialized with locale "en_IN".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/ganapati/.tethys/psql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... initdb: warning: could not open directory "/home/ganapati/miniconda3/envs/tethys/share/zoneinfo": No such file or directory
UTC0
creating configuration files ... ok
running bootstrap script ... 2021-03-25 09:05:58.461 GMT [9604] LOG:  could not open directory "/home/ganapati/miniconda3/envs/tethys/share/zoneinfo": No such file or directory
ok
performing post-bootstrap initialization ... 2021-03-25 09:05:58.543 GMT [9606] LOG:  could not open directory "/home/ganapati/miniconda3/envs/tethys/share/zoneinfo": No such file or directory
ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /home/ganapati/.tethys/psql/data -l logfile start

Starting Postgresql database server in "/home/ganapati/.tethys/psql/data" on port 5436...
waiting for server to start.... done
server started
Creating Tethys database user "tethys_super"...
DO
Creating Tethys database user "tethys_super"...
Creating Tethys database user "tethys_default"...
DO
Creating Tethys database user "tethys_default"...
Running migrations for Tethys database...
/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/jose/backends/cryptography_backend.py:23: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes
Traceback (most recent call last):
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.init_connection_state()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 211, in init_connection_state
    timezone_changed = self.ensure_timezone()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 204, in ensure_timezone
    cursor.execute(self.ops.set_time_zone_sql(), [timezone_name])
psycopg2.errors.InvalidParameterValue: invalid value for parameter "TimeZone": "UTC"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/tethys_portal/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/tethys_config/admin.py", line 14, in <module>
    from tethys_apps.admin import TethysAppSettingInline
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/tethys_apps/admin.py", line 343, in <module>
    register_custom_group()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/tethys_apps/admin.py", line 325, in register_custom_group
    class CustomGroup(GroupAdmin):
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/tethys_apps/admin.py", line 326, in CustomGroup
    form = make_gop_app_access_form()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/tethys_apps/admin.py", line 278, in make_gop_app_access_form
    for app_qs in all_apps:
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    cursor = self.connection.cursor()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.init_connection_state()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 211, in init_connection_state
    timezone_changed = self.ensure_timezone()
  File "/home/ganapati/miniconda3/envs/tethys/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 204, in ensure_timezone
    cursor.execute(self.ops.set_time_zone_sql(), [timezone_name])
django.db.utils.DataError: invalid value for parameter "TimeZone": "UTC"

ERROR!!!
(tethys) ganapati@ganapati-OptiPlex-9020:~$ tethys db configure
Initializing Postgresql database server in "/home/ganapati/.tethys/psql/data"...
The files belonging to this database system will be owned by user "ganapati".
This user must also own the server process.

The database cluster will be initialized with locale "en_IN".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/home/ganapati/.tethys/psql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/home/ganapati/.tethys/psql/data" or run initdb
with an argument other than "/home/ganapati/.tethys/psql/data".

**Comment by swainn** [comment]
This is a duplicate issue. See Issue #667
