### ISSUE TITLE
No Home Controller Found for Newly Scaffolded Apps in Tethys 4

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#789]
I installed a fresh Tethys 4 installation on Windows, scaffolded 3 apps, and installed them and I'm getting these warnings when Tethys starts:

![image](https://user-images.githubusercontent.com/5123221/163889014-e3f94db2-fcbb-41d4-a666-4d8bd7969891.png)

Visiting the app library page gives me this error:

<details>
```
ERROR:django.request:Internal Server Error: /apps/
Traceback (most recent call last):
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'my_first_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Miniconda3\envs\tethys4\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\nswain\codes\tethysplatform\tethys_apps\decorators.py", line 36, in wrapper
    return controller(request, *args, **kwargs)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\users\nswain\codes\tethysplatform\tethys_apps\views.py", line 75, in library
    return render(request, template, context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 195, in render
    return template.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 172, in render
    return self._render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'my_first_app' is not a registered namespace
ERROR:django.channels.server:HTTP GET /apps/ 500 [0.76, 127.0.0.1:63170]
ERROR:django.request:Internal Server Error: /apps/
Traceback (most recent call last):
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'my_first_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Miniconda3\envs\tethys4\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\nswain\codes\tethysplatform\tethys_apps\decorators.py", line 36, in wrapper
    return controller(request, *args, **kwargs)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\users\nswain\codes\tethysplatform\tethys_apps\views.py", line 75, in library
    return render(request, template, context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\loader_tags.py", line 195, in render
    return template.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 172, in render
    return self._render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Miniconda3\envs\tethys4\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'my_first_app' is not a registered namespace
```

The app.py of my_first_app looks like this:

``` python
from tethys_sdk.base import TethysAppBase, url_map_maker


class MyFirstApp(TethysAppBase):
    """
    Tethys app class for My First App.
    """

    name = 'My First App'
    description = ''
    package = 'my_first_app'  # WARNING: Do not change this value
    index = 'home'
    icon = f'{package}/images/icon.gif'
    root_url = 'my-first-app'
    color = '#8e44ad'
    tags = ''
    enable_feedback = False
    feedback_emails = []
```

and the controllers.py looks like this:

``` python
from django.shortcuts import render
from tethys_sdk.base import controller
from tethys_sdk.gizmos import Button

@controller
def home(request):
    """
    Controller for the app home page.
    """
    save_button = Button(
        display_text='',
        name='save-button',
        icon='save',
        style='success',
        attributes={
            'data-bs-toggle':'tooltip',
            'data-bs-placement':'top',
            'title':'Save'
        }
    )

    edit_button = Button(
        display_text='',
        name='edit-button',
        icon='pen',
        style='warning',
        attributes={
            'data-bs-toggle':'tooltip',
            'data-bs-placement':'top',
            'title':'Edit'
        }
    )

    remove_button = Button(
        display_text='',
        name='remove-button',
        icon='trash',
        style='danger',
        attributes={
            'data-bs-toggle':'tooltip',
            'data-bs-placement':'top',
            'title':'Remove'
        }
    )

    previous_button = Button(
        display_text='Previous',
        name='previous-button',
        attributes={
            'data-bs-toggle':'tooltip',
            'data-bs-placement':'top',
            'title':'Previous'
        }
    )

    next_button = Button(
        display_text='Next',
        name='next-button',
        attributes={
            'data-bs-toggle':'tooltip',
            'data-bs-placement':'top',
            'title':'Next'
        }
    )

    context = {
        'save_button': save_button,
        'edit_button': edit_button,
        'remove_button': remove_button,
        'previous_button': previous_button,
        'next_button': next_button
    }

    return render(request, 'my_first_app/home.html', context)
```
</details>

**Comment by swainn** [comment]
@sdc50 this highlights another issue: in Tethys 3 apps that have import errors would not be loaded to avoid bringing down the entire portal. This seems to no longer be the case in Tethys 4 as illustrated by this issue. Thoughts?
