### ISSUE TITLE
Map View demo not working in Gizmo Showcase app

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#810]
Steps to reproduce:

1. Install Gizmos Showcase app
2. Go to: http://localhost:8000/apps/gizmo-showcase/map-view/map-view/

Behavior:

Maps not rendering (though some of the controls are)

![image](https://user-images.githubusercontent.com/5123221/168181293-a09591bd-2aaa-4388-ac07-6d88ead7058c.png)

Expected:

Maps should render

Additional Details:

The following errors are being reported in the JavaScript console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getLayerStatesArray')
    at Group.js:305:13
    at n.forEach (Collection.js:155:7)
    at n.getLayerStatesArray (Group.js:304:22)
    at n.qe (PluggableMap.js:1491:48)
    at n.<anonymous> (PluggableMap.js:254:12)
jquery.js:4059 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at X (events.js:63:10)
    at n.Sn (Group.js:184:7)
    at n.kn (Group.js:225:10)
    at n.dispatchEvent (Target.js:111:13)
    at n.insertAt (Collection.js:203:10)
    at n.push (Collection.js:229:10)
    at n.addLayer (PluggableMap.js:564:12)
    at tethys_map_view.js:295:15
    at Array.forEach (<anonymous>)
    at ol_base_map_init (tethys_map_view.js:248:24)
Group.js:305 Uncaught TypeError: Cannot read properties of undefined (reading 'getLayerStatesArray')
    at Group.js:305:13
    at n.forEach (Collection.js:155:7)
    at n.getLayerStatesArray (Group.js:304:22)
    at n.qe (PluggableMap.js:1491:48)
    at n.<anonymous> (PluggableMap.js:254:12)
```

**Comment by swainn** [comment]
The https://demo.geo-solutions.it/geoserver/wms server is no longer functioning. Switch to HydroShare? Other source?

**Comment by swainn** [comment]
Change the basemap to be an array instead of a string:

```
# Define map view options
    map_view_options = MapView(
        height='600px',
        width='100%',
        controls=['ZoomSlider', 'Rotate', 'FullScreen',
                  {'MousePosition': {'projection': 'EPSG:4326'}},
                  {'ZoomToExtent': {'projection': 'EPSG:4326', 'extent': [-130, 22, -65, 54]}}],
        layers=map_layers,
        view=view_options,
        basemap=['OpenStreetMap'],
        draw=drawing_options,
        legend=True
    )
```
