### ISSUE TITLE
Ceisum Map View is not rendering in Gizmo Showcase app

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#811]
Steps to reproduce:

1. Install Gizmos Showcase app
2. Go to: http://localhost:8000/apps/gizmo-showcase/cesium-map-view/

Behavior:

Cesium map not rendering 

![image](https://user-images.githubusercontent.com/5123221/168181575-f2d31809-2e0e-4c78-b9a4-35a11ff0091d.png)

Expected:

Cesium map should render

Additional Details:

The following errors are being reported in the JavaScript console:

```
GET https://cdn.jsdelivr.net/npm/cesium@1.88/Build/CesiumUnminified/CesiumUnminified.js net::ERR_ABORTED 404
DrawHelper.min.js:1 Uncaught ReferenceError: Cesium is not defined
    at DrawHelper.min.js:1:42
    at DrawHelper.min.js:164:11
(anonymous) @ DrawHelper.min.js:1
(anonymous) @ DrawHelper.min.js:164
jquery.js:4050 jQuery.Deferred exception: Cesium is not defined ReferenceError: Cesium is not defined
    at cesium_base_map_init (http://localhost:8000/static/tethys_gizmos/js/cesium_map_view.js:61:9)
    at cesium_initialize_all (http://localhost:8000/static/tethys_gizmos/js/cesium_map_view.js:548:9)
    at HTMLDocument.<anonymous> (http://localhost:8000/static/tethys_gizmos/js/cesium_map_view.js:896:3)
    at mightThrow (https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.js:3766:29)
    at process (https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.js:3834:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:4050
process @ jquery.js:3838
setTimeout (async)
(anonymous) @ jquery.js:3872
fire @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
fire @ jquery.js:3500
fireWith @ jquery.js:3630
ready @ jquery.js:4110
completed @ jquery.js:4120
jquery.js:4059 Uncaught ReferenceError: Cesium is not defined
    at cesium_base_map_init (cesium_map_view.js:61:9)
    at cesium_initialize_all (cesium_map_view.js:548:9)
    at HTMLDocument.<anonymous> (cesium_map_view.js:896:3)
    at mightThrow (jquery.js:3766:29)
    at process (jquery.js:3834:12)
```

**Comment by swainn** [comment]
@sdc50 this one was working before merging your CDN PR. Want to take a look?
