### ISSUE TITLE
Esri Map View is not working in Gizmo showcase app

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#812]
Steps to reproduce:

1. Install Gizmos Showcase app
2. Go to: http://localhost:8000/apps/gizmo-showcase/esri-map-view/esri-map-view/

Behavior:

Esri map not rendering 

Expected:

Esri map should render

Additional Details:

The following errors are being reported in the JavaScript console:

```
localhost/:52          GET https://js.arcgis.com/4.22.2/esri/css/main.css net::ERR_ABORTED 404
localhost/:93          GET https://js.arcgis.com/4.22.2/init.js net::ERR_ABORTED 404
jquery.js:4050 jQuery.Deferred exception: require is not defined ReferenceError: require is not defined
    at esri_base_map_init (http://localhost:8000/static/tethys_gizmos/js/esri_map.js:71:9)
    at esri_initialize_all (http://localhost:8000/static/tethys_gizmos/js/esri_map.js:207:9)
    at HTMLDocument.<anonymous> (http://localhost:8000/static/tethys_gizmos/js/esri_map.js:243:9)
    at mightThrow (https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.js:3766:29)
    at process (https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.js:3834:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:4050
process @ jquery.js:3838
setTimeout (async)
(anonymous) @ jquery.js:3872
fire @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
fire @ jquery.js:3500
fireWith @ jquery.js:3630
ready @ jquery.js:4110
completed @ jquery.js:4120
jquery.js:4059 Uncaught ReferenceError: require is not defined
    at esri_base_map_init (esri_map.js:71:9)
    at esri_initialize_all (esri_map.js:207:9)
    at HTMLDocument.<anonymous> (esri_map.js:243:9)
    at mightThrow (jquery.js:3766:29)
    at process (jquery.js:3834:12)
```

**Comment by swainn** [comment]
@sdc50 this one was also working prior to your CDN PR
