### ISSUE TITLE
tethys db configure ERROR

### ISSUE THREAD

**Issue by acatlett8** [tethysplatform/tethys#879]
I am trying to set up tethys and i'm using the following commands. I get an error and i'm not sure why. I'm on a MAC

Commands i ran:
# Setup keys 
tethys settings -s INSTALLED_APPS "['uit_plus_job']"
tethys settings -s AUTHENTICATION_BACKENDS "['uit_plus_job.oauth2.UitPlusOAuth2']"
tethys settings -s OAUTH_CONFIG.SOCIAL_AUTH_UITPLUS_KEY "c2eebe7f-da59-4db9-96b0-8c8e4a42a0ae"
tethys settings -s OAUTH_CONFIG.SOCIAL_AUTH_UITPLUS_SECRET "91178fe9e9a2ac1aefcbdcfb0988651f"
# Configure the database 
tethys db configure

# Printed to terminal: 
Initializing Postgresql database server in "/Users/rditlar9/.tethys/base/psql/data"...
The files belonging to this database system will be owned by user "rditlar9".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /Users/rditlar9/.tethys/base/psql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /Users/rditlar9/.tethys/base/psql/data -l logfile start

Starting Postgresql database server in "/Users/rditlar9/.tethys/base/psql/data" on port 5436...
waiting for server to start.... done
server started
Creating Tethys database user "tethys_super"...
DO
Creating Tethys database user "tethys_super"...
Creating Tethys database user "tethys_default"...
DO
Creating Tethys database user "tethys_default"...
Running migrations for Tethys database...
Loading Tethys Extensions...
Loading Tethys Apps...
ERROR:tethys.app_base:The following error occurred while trying to import the controller function "helios.controllers.home":
 Traceback (most recent call last):
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_apps/base/app_base.py", line 77, in _resolve_ref_function
    module = __import__(module_name, fromlist=[function_name])
  File "/Users/rditlar9/workplace/RAD/helios/tethysapp-helios_workflows/tethysapp/helios/controllers.py", line 23, in <module>
    from uit_plus_job.models import UitPlusJob
ImportError: cannot import name 'JSONField' from 'django.db.models' (/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/db/models/__init__.py)

ERROR:tethys.tethys_apps.harvester:App tethysapp.helios not loaded because of an issue with loading urls:
Traceback (most recent call last):
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_apps/harvester.py", line 267, in _harvest_app_instances
    app_instance.url_patterns
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_apps/base/app_base.py", line 198, in url_patterns
    controller_function = self._resolve_ref_function(url_map.controller, 'controller', is_extension)
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_apps/base/app_base.py", line 82, in _resolve_ref_function
    raise e
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_apps/base/app_base.py", line 77, in _resolve_ref_function
    module = __import__(module_name, fromlist=[function_name])
  File "/Users/rditlar9/workplace/RAD/helios/tethysapp-helios_workflows/tethysapp/helios/controllers.py", line 23, in <module>
    from uit_plus_job.models import UitPlusJob
  File "/Users/rditlar9/workplace/RAD/helios/django-uit_job_type/uit_plus_job/models.py", line 17, in <module>
    from django.db.models import JSONField
ImportError: cannot import name 'JSONField' from 'django.db.models' (/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/db/models/__init__.py)
ERROR:tethys.app_base:relation "tethys_apps_tethysapp" does not exist
LINE 1: ...ethys_apps_tethysapp"."show_in_apps_library" FROM "tethys_ap...
                                                             ^

Tethys Apps Loaded:

Traceback (most recent call last):
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_portal/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_portal/urls.py", line 21, in <module>
    from tethys_portal.views import accounts as tethys_portal_accounts, developer as tethys_portal_developer, \
  File "/Users/rditlar9/workplace/RAD/helios/tethys/tethys_portal/views/accounts.py", line 17, in <module>
    from mfa.helpers import has_mfa
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/mfa/helpers.py", line 3, in <module>
    from . import TrustedDevice, U2F, FIDO2, totp
  File "/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/mfa/FIDO2.py", line 1, in <module>
    from fido2.client import ClientData
ImportError: cannot import name 'ClientData' from 'fido2.client' (/Users/rditlar9/miniconda/envs/helios/lib/python3.7/site-packages/fido2/client.py)
ERROR!!!

**Comment by swainn** [comment]
Hi @acatlett8 sorry you are having trouble. This looks like it might be similar to #838.

Take a look at the output of the following commands:

```
tethys version
```

```
conda list
```

For Tethys version 3.X, fido2 must be <1

**Comment by acatlett8** [comment]
My tethys version is 3.4.0.dev150 and the fido2 is 0.9.3

**Comment by swainn** [comment]
Ah, I see. Confusingly, 3.4.0.devXXX is actually a dev version of Tethys 4. We've since updated our CI so that we can tag dev versions more appropriately. For Tethys 4, fido2 needs to be >1. So this is actually the opposite of #838.

There is an official release candidate for Tethys 4 now, I'd recommend using that if you are testing Tethys 4. You can find install instructions on this Discussion post: #878

**Comment by acatlett8** [comment]
I updated to tethys version: 4.0.0rc2.dev0+gb3214c66.d20221023. i'm getting 
Initializing Postgresql database server in "/Users/rditlar9/.tethys/base/psql/data"...
The files belonging to this database system will be owned by user "rditlar9".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /Users/rditlar9/.tethys/base/psql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /Users/rditlar9/.tethys/base/psql/data -l logfile start

Starting Postgresql database server in "/Users/rditlar9/.tethys/base/psql/data" on port 5436...
waiting for server to start.... done
server started
Creating Tethys database user "tethys_super"...
DO
Creating Tethys database user "tethys_super"...
Creating Tethys database user "tethys_default"...
DO
Creating Tethys database user "tethys_default"...
Running migrations for Tethys database...
WARNING:tethys.tethys_apps.admin:Unable to register CustomGroup.
WARNING:tethys.tethys_apps.admin:Unable to register CustomGroup.
Loading Tethys Extensions...
Loading Tethys Apps...
ERROR:tethys.tethys_apps.harvester:App tethysapp.helios not loaded because of the following error:
Traceback (most recent call last):
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/harvester.py", line 269, in _harvest_app_instances
    app_module = __import__(app_package + ".app", fromlist=[""])
  File "/Users/rditlar9/workplace/RAD/helios-main/tethysapp-helios_workflows/tethysapp/helios/app.py", line 1, in <module>
    from tethys_sdk.base import TethysAppBase, url_map_maker
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_sdk/base.py", line 13, in <module>
    from tethys_apps.base.controller import TethysController
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/base/controller.py", line 55
    /,
    ^
SyntaxError: invalid syntax
ERROR:tethys.tethys_apps.harvester:App tethysapp.helios not loaded because of the following error:
Traceback (most recent call last):
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/harvester.py", line 269, in _harvest_app_instances
    app_module = __import__(app_package + ".app", fromlist=[""])
  File "/Users/rditlar9/workplace/RAD/helios-main/tethysapp-helios_workflows/tethysapp/helios/app.py", line 1, in <module>
    from tethys_sdk.base import TethysAppBase, url_map_maker
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_sdk/base.py", line 13, in <module>
    from tethys_apps.base.controller import TethysController
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/base/controller.py", line 55
    /,
    ^
SyntaxError: invalid syntax
Tethys Apps Loaded:

WARNING:tethys.tethys_quotas.apps:Unable to sync resource quota handlers: Resource Quota table does not exist
WARNING:tethys.tethys_quotas.apps:Unable to sync resource quota handlers: Resource Quota table does not exist
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, captcha, contenttypes, guardian, mfa, sessions, social_django, termsandconditions, tethys_apps, tethys_compute, tethys_config, tethys_quotas, tethys_services
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying axes.0001_initial... OK
  Applying axes.0002_auto_20151217_2044... OK
  Applying axes.0003_auto_20160322_0929... OK
  Applying axes.0004_auto_20181024_1538... OK
  Applying axes.0005_remove_accessattempt_trusted... OK
  Applying axes.0006_remove_accesslog_trusted... OK
  Applying axes.0007_alter_accessattempt_unique_together... OK
  Applying captcha.0001_initial... OK
  Applying guardian.0001_initial... OK
  Applying guardian.0002_generic_permissions_index... OK
  Applying mfa.0001_initial... OK
  Applying mfa.0002_user_keys_key_type... OK
  Applying mfa.0003_auto_20181114_2159... OK
  Applying mfa.0004_user_keys_enabled... OK
  Applying mfa.0005_auto_20181115_2014... OK
  Applying mfa.0006_trusted_devices... OK
  Applying mfa.0007_auto_20181230_1549... OK
  Applying mfa.0008_user_keys_last_used... OK
  Applying mfa.0009_user_keys_owned_by_enterprise... OK
  Applying mfa.0010_auto_20201110_0557... OK
  Applying mfa.0011_auto_20210530_0622... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
  Applying social_django.0009_auto_20191118_0520... OK
  Applying social_django.0010_uid_db_index... OK
  Applying termsandconditions.0001_initial... OK
  Applying termsandconditions.0002_termsandconditions_info... OK
  Applying termsandconditions.0003_auto_20170627_1217... OK
  Applying tethys_services.0001_initial_40... OK
  Applying tethys_compute.0001_initial_40... OK
  Applying tethys_apps.0001_initial_40... OK
  Applying tethys_config.0001_initial_40... OK
  Applying tethys_quotas.0001_initial_40... OK
Creating Tethys Portal superuser "admin"...
ERROR:tethys.tethys_apps.harvester:App tethysapp.helios not loaded because of the following error:
Traceback (most recent call last):
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/harvester.py", line 269, in _harvest_app_instances
    app_module = __import__(app_package + ".app", fromlist=[""])
  File "/Users/rditlar9/workplace/RAD/helios-main/tethysapp-helios_workflows/tethysapp/helios/app.py", line 1, in <module>
    from tethys_sdk.base import TethysAppBase, url_map_maker
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_sdk/base.py", line 13, in <module>
    from tethys_apps.base.controller import TethysController
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/base/controller.py", line 55
    /,
    ^
SyntaxError: invalid syntax
ERROR:tethys.tethys_apps.harvester:App tethysapp.helios not loaded because of the following error:
Traceback (most recent call last):
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/harvester.py", line 269, in _harvest_app_instances
    app_module = __import__(app_package + ".app", fromlist=[""])
  File "/Users/rditlar9/workplace/RAD/helios-main/tethysapp-helios_workflows/tethysapp/helios/app.py", line 1, in <module>
    from tethys_sdk.base import TethysAppBase, url_map_maker
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_sdk/base.py", line 13, in <module>
    from tethys_apps.base.controller import TethysController
  File "/Users/rditlar9/miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/base/controller.py", line 55
    /,
    ^
SyntaxError: invalid syntax

**Comment by swainn** [comment]
@acatlett8 I saw that you were having issues with the Tethys release candidate in an email, but I don't see the comment here. Basically amounted to this:

```
File ".../miniconda/envs/tethys/lib/python3.7/site-packages/tethys_apps/base/controller.py", line 55
/,
^
SyntaxError: invalid syntax
```

I think the issue here is that Tethys 4 requires Python >= 3.8 and it looks like you installed the Tethys 4 package into an existing Python 3.7 environment?

**Comment by acatlett8** [comment]
yeah i had another error but after i posted this i check fido2 and saw it was not the correct version. going to be trying again. thanks for your responses
