### ISSUE TITLE
[BUG] Tethys install command fails when libmamba is set to default solver

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#943]
**Describe the bug**
The `tethys install` command fails when `libmamba` solver is set as default (`conda config --set solver libmamba`).

**To Reproduce**
1. Install `libmamba` solver and set as default solver per these directions: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community/
2. Try to install an app in Tethys

**Expected behavior**
It should install using `libmamba` or at least not fail if that isn't possible.

**Errors/Traceback**

<details>

```bash
tethys install -d
Installing dependencies...
Running conda installation tasks...
Retrieving notices: ...working... done
Traceback (most recent call last):
  File "/home/tethysdev/miniconda3/envs/tethys/bin/tethys", line 8, in <module>
    sys.exit(tethys_command())
             ^^^^^^^^^^^^^^^^
  File "/home/tethysdev/tethys/tethys_cli/__init__.py", line 67, in tethys_command
    args.func(args)
  File "/home/tethysdev/tethys/tethys_cli/install_commands.py", line 750, in install_command
    install_packages(
  File "/home/tethysdev/tethys/tethys_cli/install_commands.py", line 680, in install_packages
    [resp, err, code] = conda_run(
                        ^^^^^^^^^^
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/cli/python_api.py", line 118, in run_command
    raise e
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/cli/python_api.py", line 107, in run_command
    result = do_call(args, p)
             ^^^^^^^^^^^^^^^^
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
    return getattr(module, func_name)(args, parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/notices/core.py", line 116, in wrapper    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/cli/install.py", line 248, in install
    solver_backend = context.plugin_manager.get_cached_solver_backend()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.11/site-packages/conda/plugins/manager.py", line 149, in get_solver_backend
    raise CondaValueError(
conda.exceptions.CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```

</details>

**Screenshots**
N/A

**Tethys Environment Information**
Include output from these commands:
- tethys version
- conda info
- conda list

**Additional context**

**Comment by swainn** [comment]
This appears to be an issue with conda libmamba solver package's support for the Python API. Posted an issue: https://github.com/conda/conda-libmamba-solver/issues/202

**Comment by swainn** [comment]
> This appears to be an issue with conda libmamba solver package's support for the Python API. Posted an issue: [conda/conda-libmamba-solver#202](https://github.com/conda/conda-libmamba-solver/issues/202)
