### ISSUE TITLE
Dockers Fail to Start on Mac OS X Development Installation

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#96]
Seems related to the restart policy:

The Docker containers have been successfully installed.
(tethys)NLJ-MBP:~ Norm$ tethys docker start
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/key.pem
Starting PostGIS container...
Traceback (most recent call last):
  File "/usr/lib/tethys/bin/tethys", line 9, in <module>
    load_entry_point('tethys-platform==1.1.0', 'console_scripts', 'tethys')()
  File "/usr/lib/tethys/src/tethys_apps/cli/__init__.py", line 246, in tethys_command
    args.func(args)
  File "/usr/lib/tethys/src/tethys_apps/cli/__init__.py", line 108, in docker_command
    docker_start(container=args.container)
  File "/usr/lib/tethys/src/tethys_apps/cli/docker_commands.py", line 727, in docker_start
    start_docker_containers(docker_client, container=container)
  File "/usr/lib/tethys/src/tethys_apps/cli/docker_commands.py", line 573, in start_docker_containers
    port_bindings={5432: DEFAULT_POSTGIS_PORT})
  File "/usr/lib/tethys/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/tethys/lib/python2.7/site-packages/docker/client.py", line 1076, in start
    self._raise_for_status(res)
  File "/usr/lib/tethys/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal string into Go value of type runconfig.RestartPolicy")
(tethys)NLJ-MBP:~ Norm$ tethys docker ip
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/key.pem
PostGIS/Database: Not Running.
GeoServer: Not Running.
52 North WPS: Not Running.
(tethys)NLJ-MBP:~ Norm$

**Comment by swainn** [comment]
More strange behavior:

(tethys)NLJ-MBP:~ Norm$ tethys docker start
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/key.pem
PostGIS container already running...
GeoServer container already running...
52 North WPS container already running...

(tethys)NLJ-MBP:~ Norm$ tethys docker ip
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/Norm/.boot2docker/certs/boot2docker-vm/key.pem
PostGIS/Database: Not Installed.
GeoServer: Not Installed.
52 North WPS: Not Installed.

Running, but not installed????? This may have to do with the fact that we started the containers manually and not through the Tethys CLI.

**Comment by zhiyuli** [comment]
@swainn  @sdc50  @ezrajrice 
I found this post on Google.....I got the same error on CentOS 7. I am installing Tethys 1.2 on CentOS 7 because its system python is 2.7...The only thing I can tell about this error is that docker version on CentOS 6 is 1.6.2  and on CentOS 7 it is 1.7.1
![image](https://cloud.githubusercontent.com/assets/10070599/9646677/223ed968-5193-11e5-8d26-a690ea16d37d.png)


(tethys)[root@tmplab-115-212 drew]# tethys docker start
Starting PostGIS container...
Traceback (most recent call last):
  File "/usr/lib/tethys/bin/tethys", line 9, in <module>
    load_entry_point('tethys-platform==1.2.1', 'console_scripts', 'tethys')()
  File "/usr/lib/tethys/src/tethys_apps/cli/__init__.py", line 256, in tethys_command
    args.func(args)
  File "/usr/lib/tethys/src/tethys_apps/cli/__init__.py", line 118, in docker_command
    docker_start(container=args.container)
  File "/usr/lib/tethys/src/tethys_apps/cli/docker_commands.py", line 737, in docker_start
    start_docker_containers(docker_client, container=container)
  File "/usr/lib/tethys/src/tethys_apps/cli/docker_commands.py", line 583, in start_docker_containers
    port_bindings={5432: DEFAULT_POSTGIS_PORT})
  File "/usr/lib/tethys/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/tethys/lib/python2.7/site-packages/docker/client.py", line 1076, in start
    self._raise_for_status(res)
  File "/usr/lib/tethys/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal string into Go value of type runconfig.RestartPolicy")
(tethys)[root@tmplab-115-212 drew]# docker ps

**Comment by swainn** [comment]
We are dropping official support for Mac OSX.
